name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  
jobs:
  release-please:
    runs-on: [self-hosted, label-1]
    steps:
      - uses: googleapis/release-please-action@v4.2.0
        with:
          token: ${{ secrets.GH_TOKEN }}
          release-type: simple
